language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'
  - '8.1'
  - '8.2'
  - '8.3'

before_script:
  - composer -n --prefer-source install

script:
  - bin/phpunit
  - bin/phpcs
  - bin/phpstan analyse
  - bin/infection --formatter=progress
